version: '3'
services:
  app:
    build: ./..
    ports:
      - 16001:16001
    volumes:
      - ../node_modules:/app/node_modules
      - ../src:/app/src
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../tsconfig.json:/app/tsconfig.json
    env_file: '.env'
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file: '.env'