version: '3'
services:
  app:
    build: ./../Dockerfile
    ports:
      - 16001:16001
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: app
    ports:
      - 5432:5432